steps:
  - label: ":building_construction: Build that code then trigger another :pipeline:"
    command: "echo Building"
  - label: "Trigger separate pipeline"
    trigger: pipeline-that-gets-triggered
agents:
  queue: "q1"
