steps:
  - group: ":rocket: :aws: Parallel Dev Deploys"
    key: "dev_deploys"
    steps:
    - label: ":ec2: dev_sm_x86_us-east-1"
      command: "echo Deploying to Intel us-east-1"
    - label: ":ec2: dev_sm_arm_us-east-1"
      command: "echo Deploying to ARM us-east-1"
    - label: ":ec2: dev_sm_x86_us-west-2"
      command: "echo Deploying to Intel us-west-2"
    - label: ":ec2: dev_med_arm_us-west-2"
      command: "echo Deploying to ARM us-west-2"
    - label: ":ec2: dev_sm_x86_us-central-1"
      command: "echo Deploying to Intel us-central-1"
    - label: ":ec2: dev_med_arm_us-central-1"
      command: "echo Deploying to ARM us-central-1"
    - label: ":ec2: dev_sm_x86_eu-central-1"
      command: "echo Deploying to Intel eu-central-1"
    - label: ":ec2: dev_med_arm_eu-central-1"
      command: "echo Deploying to ARM eu-central-1"
  - group: ":rocket: :aws: Parallel Staging Deploys"
    key: "stg_deploys"
    steps:
    - label: ":ec2: stg_sm_x86_us-east-1"
      command: "echo Deploying to Intel us-east-1"
    - label: ":ec2: stg_sm_arm_us-east-1"
      command: "echo Deploying to ARM us-east-1"
    - label: ":ec2: stg_sm_x86_us-west-2"
      command: "echo Deploying to Intel us-west-2"
    - label: ":ec2: stg_med_arm_us-west-2"
      command: "echo Deploying to ARM us-west-2"
    - label: ":ec2: stg_sm_x86_us-central-1"
      command: "echo Deploying to Intel us-central-1"
    - label: ":ec2: stg_med_arm_us-central-1"
      command: "echo Deploying to ARM us-central-1"
    - label: ":ec2: stg_sm_x86_eu-central-1"
      command: "echo Deploying to Intel eu-central-1"
    - label: ":ec2: stg_med_arm_eu-central-1"
      command: "echo Deploying to ARM eu-central-1"
    depends_on:
      - "dev_deploys"
  - group: ":rocket: :aws: Parallel QA Deploys"
    key: "qa_deploys"
    steps:
    - label: ":ec2: qa_sm_x86_us-east-1"
      command: "echo Deploying to Intel us-east-1"
    - label: ":ec2: qa_sm_arm_us-east-1"
      command: "echo Deploying to ARM us-east-1"
    - label: ":ec2: qa_sm_x86_us-west-2"
      command: "echo Deploying to Intel us-west-2"
    - label: ":ec2: qa_med_arm_us-west-2"
      command: "echo Deploying to ARM us-west-2"
    - label: ":ec2: qa_sm_x86_us-central-1"
      command: "echo Deploying to Intel us-central-1"
    - label: ":ec2: qa_med_arm_us-central-1"
      command: "echo Deploying to ARM us-central-1"
    - label: ":ec2: qa_sm_x86_eu-central-1"
      command: "echo Deploying to Intel eu-central-1"
    - label: ":ec2: qa_med_arm_eu-central-1"
      command: "echo Deploying to ARM eu-central-1"
  - group: ":rocket: :aws: Parallel Pre-Prod Deploys"
    key: "pre_deploys"
    steps:
    - label: ":ec2: pre_sm_x86_us-east-1"
      command: "echo Deploying to Intel us-east-1"
    - label: ":ec2: pre_sm_arm_us-east-1"
      command: "echo Deploying to ARM us-east-1"
    - label: ":ec2: pre_sm_x86_us-west-2"
      command: "echo Deploying to Intel us-west-2"
    - label: ":ec2: pre_med_arm_us-west-2"
      command: "echo Deploying to ARM us-west-2"
    - label: ":ec2: pre_sm_x86_us-central-1"
      command: "echo Deploying to Intel us-central-1"
    - label: ":ec2: pre_med_arm_us-central-1"
      command: "echo Deploying to ARM us-central-1"
    - label: ":ec2: pre_sm_x86_eu-central-1"
      command: "echo Deploying to Intel eu-central-1"
    - label: ":ec2: pre_med_arm_eu-central-1"
      command: "echo Deploying to ARM eu-central-1"
    depends_on:
      - "qa_deploys"
queue: "q1"
