steps:
  - label: ":building_construction: Build that BOXY code :hammer_and_wrench:"
    command: "echo Building"
  - label: ":lint-roller: Lint for codestyle"
    command: "echo Linting"
  - label: ":test_tube: Run tests"
    command: "echo Running Tests in parallel"
  - label: ":coverage: Check codecov"
    command: "echo Gathering code coverage numbers"
  - label: ":nsp: :male-detective: Security Scan"
    command: "echo Security Scan"
  - label: ":sonarqube: Send to Sonar"
    command: "echo Static Code Analysis"
  - label: ":bazel: bb-cluster-1"
    command: "echo Remote execution to bb-cluster-1"
  - label: ":bazel: bb-cluster-1"
    command: "echo Remote execution to bb-cluster-1"
  - label: ":bazel: bb-cluster-1"
    command: "echo Remote execution to bb-cluster-2"
  - label: ":bazel: bb-cluster-2"
    command: "echo Remote execution to bb-cluster-3"
  - label: ":bazel: bb-cluster-1"
    command: "echo Remote execution to bb-cluster-1"
  - label: ":bazel: bb-cluster-3"
    command: "echo Remote execution to bb-cluster-3"
  - label: ":bazel: bb-cluster-2"
    command: "echo Remote execution to bb-cluster-2"
  - label: ":bazel: bb-cluster-3"
    command: "echo Remote execution to bb-cluster-3"
  - label: ":bazel: bb-cluster-1"
    command: "echo Remote execution to bb-cluster-1"
  - label: ":bazel: bb-cluster-4"
    command: "echo Remote execution to bb-cluster-4"
  - label: ":bazel: bb-cluster-2"
    command: "echo Remote execution to bb-cluster-2"
  - label: ":bazel: bb-cluster-5"
    command: "echo Remote execution to bb-cluster-5"
  - label: ":bazel: bb-cluster-2"
    command: "echo Remote execution to bb-cluster-2"
  - label: ":bazel: bb-cluster-3"
    command: "echo Remote execution to bb-cluster-3"
  - label: ":bazel: bb-cluster-1"
    command: "echo Remote execution to bb-cluster-1"
  - label: ":bazel: bb-cluster-4"
    command: "echo Remote execution to bb-cluster-4"
  - label: ":bazel: bb-cluster-1"
    command: "echo Remote execution to bb-cluster-1"
  - label: ":bazel: bb-cluster-5"
    command: "echo Remote execution to bb-cluster-5"
  - label: ":bazel: bb-cluster-2"
    command: "echo Remote execution to bb-cluster-2"
  - label: ":bazel: bb-cluster-4"
    command: "echo Remote execution to bb-cluster-4"
  - label: ":bazel: bb-cluster-2"
    command: "echo Remote execution to bb-cluster-2"
  - label: ":bazel: bb-cluster-3"
    command: "echo Remote execution to bb-cluster-3"
  - label: ":bazel: bb-cluster-1"
    command: "echo Remote execution to bb-cluster-1"
  - label: ":bazel: bb-cluster-5"
    command: "echo Remote execution to bb-cluster-5"
queue: "k8sdefault"
