steps:
  - label: ":building_construction: Build that SAFE code :hammer_and_wrench:"
    command: "echo Building"
    key: "da_build"
  - group: ":test_tube: :lint-roller: Testing and Linting"
    key: "tests"
    steps:
    - label: ":lint-roller: Lint for codestyle"
      command: "echo Linting"
    - label: ":test_tube: Run tests"
      command: "echo Running Tests in parallel"
    - label: ":coverage: Check codecov"
      command: "echo Gathering code coverage numbers"
  - group: ":lock_with_ink_pen: Security Checks Are Good Practice"
    key: "audits"
    steps:
    - label: ":nsp: :male-detective: Security Scan"
      command: "echo Security Scan"
    - label: ":sonarqube: Send to Sonar"
      command: "echo Static Code Analysis"
  - block: ":grey_question: Deploy to Dev?"
    depends_on:
      - "da_build"
      - "audits"
      - "tests"
    key: "dev_block"
  - group: ":rocket: :aws: Parallel Dev Deploys"
    key: "devvy_deploys"
    steps:
    - label: ":ec2: dev_sm_x86_us-east-1"
      command: "echo Deploying to Intel us-east-1"
    - label: ":ec2: dev_sm_arm_us-east-1"
      command: "echo Deploying to ARM us-east-1"
    depends_on:
      - "dev_block"
  - block: ":grey_question: Deploy to Staging?"
    depends_on:
      - "da_build"
      - "audits"
      - "tests"
    key: "stg_block"
  - group: ":rocket: :aws: Parallel Staging Deploys"
    key: "stggy_deploys"
    steps:
    - label: ":ec2: stg_sm_x86_us-east-1"
      command: "echo Deploying to Intel us-east-1"
    - label: ":ec2: stg_sm_arm_us-east-1"
      command: "echo Deploying to ARM us-east-1"
    depends_on:
      - "stg_block"
  - block: ":question: Deploy to Prod?"
    depends_on:
      - "devvy_deploys"
      - "stggy_deploys"
    key: "prod_block"
  - block: ":warning: :question: ARE YOU SURE? Deploy to Prod? :warning:"
    depends_on:
      - "prod_block"
    key: "sure_block"
  - group: ":rocket: :aws: Parallel Production Deploys"
    key: "prod_deploys"
    steps:
    - label: ":ec2: prod_sm_x86_us-east-1"
      command: "echo Deploying to Intel us-east-1"
    - label: ":ec2: prod_sm_arm_us-east-1"
      command: "echo Deploying to ARM us-east-1"
    depends_on:
      - "sure_block"
agents:
  queue: "q1"
